#SPDX-License-Identifier: MIT-0
---
# handlers file for node-on-win
- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart application service
  ansible.builtin.systemd:
    name: "container-{{ application_container_name }}.service"
    state: restarted
